# Generated by Django 5.2.17 on 2026-08-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
